
  var kartData=[
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51PCoFrVIJL.jpg",
    name: "Implementing SAP S/4HANA Finance",
    price: "4843.0",
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51NoZdbMRFL.jpg",
    name: "Edexcel International GCSE German Grammar Workbook Second Edition",
    price: "471.0",
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51-kUPlIpiL.jpg",
    name: "Class 10: Work Book & Reasoning Book Combo for NSO-IMO-IEO-NCO-IGKO (2018-19)",
    price: "405.0",
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/41k-ouQ9o7L.jpg",
    name: "The Application of an Explicit Numerical Method to a Reaction-Diffusion System in Combustion (Classic Reprint)",
    price: "659.0",
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51Xjd%2BpXYQL.jpg",
    name: "Webby Learning Educational Wooden Small Alphabets Letters Tray Toy for Kids",
    price: "266.0",
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/410MiUwdIuL.jpg",
    name: "Rewrite Your Destiny: Do Not Let the Destiny Decide The End of Your Story",
    price: "300.0",
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51H1Q-jJtyL.jpg",
    name: "Basic Science & Engineering for Indian Railways (RRB) Assistant Loco Pilot Exam 2018 Stage II",
    price: "108.0",
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51vGFrkejAL.jpg",
    name: "Zigyasaw Hindi Alphabets Flash Cards",
    price: "299.0",
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51U2%2BEota0L.jpg",
    name: "Elixir in Action, Second Edition",
    price: "3886.0",
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/41UyCVVJAXL.jpg",
    name: "COI Brown Faux Leather Front Pocket Corporate Executive Travel Diary Budget Planner Organizer 2019. Gift for Man",
    price: "999.0",
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51HjCeriOlL.jpg",
    name: "Barron's SAT Subject Test Math Level 1",
    price: "360.0",
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/41JUBDkCurL.jpg",
    name: "GRE Prep Plus 2020",
    price: "",
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/315AKYIC08L.jpg",
    name: "Educational Teddy Stacking Ring Big(7 Rings). let Your Child Learn Different Colours, Stacking and Sorting",
    price: "179.0",
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51oJ4XwIxSL.jpg",
    name: "Olympiad Reasoning Workbook - Class 3",
    price: "143.0",
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51DpqqO4TiL.jpg",
    name: "Inner Engineering (Hindi): A Yogi's Guide",
    price: 149.0,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51AQr0jgE2L.jpg",
    name: "Diagnostic Radiology: Neuroradiology including Head and Neck Imaging",
    price: 2750.0,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/41ysR%2BK%2BVLL.jpg",
    name: "ACT Designer Silk Thread Bangles Reddish brown Colour, A pair of 3 Bangles (Size : 2x4)",
    price: 220.0,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/41Gb0%2BTy-OL.jpg",
    name: "Why People Give",
    price: 338.0,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51FB5z-00qL.jpg",
    name: "Structure and Function in Primitive Society: Essays and Addresses (Classic Reprint)",
    price: 779.0,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51pTPVze95L.jpg",
    name: "O Level Made Easy Complete Theory plus Practice Book For IT Tools & Network Basis (DOEACC M1-R5) in Hindi and English 2020",
    price: 178.0,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/41g9cvmPcYL.jpg",
    name: "Lovely War",
    price: 495.0,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51wyKqo5JtL.jpg",
    name: "GATE Electronics and Communication Engineering | GATE 2020 | By Pearson",
    price: 700.0,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51FpxIPSk9L.jpg",
    name: "The Old Farmer's Almanac 2020",
    price:476.0 ,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  
  {
    image_url:
      "https://images-eu.ssl-images-amazon.com/images/I/515dzir8fdL.jpg",
    name: "Ramamurthy's Decision Making in Pain Management: An Algorithmic Approach ",
    price: 1226.0,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
    
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51jg5RzK9rL.jpg",
    name: "Laura Dean Keeps Breaking Up with Me",
    price: 1176.0,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51BeMkreLrL.jpg",
    name: "GATE and PGECET for Computer Science and Information Technology",
    price:594.0 ,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/41BSQay88AL.jpg",
    name: "Handbook on Debt Recovery (Tamil) (2019 Edition)",
    price: 445.0,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/41V%2Bt7MEzoL.jpg",
    name: "Be Fearless",
    price: 339.0,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51GVj8%2B0FBL.jpg",
    name: "The Vedï¿½nta-Sï¿½tras, Vol. 1: With the Commentary by Sankarï¿½kï¿½rya (Classi",
    price:1388.41 ,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51tfrz3ahnL.jpg",
    name: "Barron's AP English Literature and Composition (Barron's Ap English Literture and Composition)",
    price:1021.06 ,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/511xPmfY91L.jpg",
    name: "Auroville A Dream Hijacked",
    price:290.0 ,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51-wyjldXxL.jpg",
    name: "Escape from Earth: A Secret History of the Space Rocket",
    price:1378.0 ,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/41ZYjVE-qVL.jpg",
    name: "The Prince",
    price:430.0 ,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/61kMMml7EkL.jpg",
    name: "Redeeming Money: How God Reveals and Reorients Our Hearts",
    price:1063.0 ,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/41yz86878EL.jpg",
    name: "Innovator's DNA, Updated, with a New Introduction",
    price:858.0 ,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/41F0INBi25L.jpg",
    name: "WP Infinity Cube Fidget Cube Toy for Adults & Kids Relieve Stress & Anxiety Hand Fidget Stress Reducer Best for ADD,ADHD,OCD,Anxiety Disorder,Autism(Multi Colour)",
    price:99.0 ,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/51oW4MBO7pL.jpg",
    name: "Guide to Judicial Service Mains Examination - Vol.1",
    price:490.0 ,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/41JQdGP-V5L.jpg",
    name: "wondergirls Preferred Prop Money Play Money Full Print New Money Copy of 100 Dollar Bills Stack(None American Version 100)",
    price: 398.13,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://images-eu.ssl-images-amazon.com/images/I/613aj5JNK-L.jpg",
    name: "Tom Gates #14: Biscuits Bands and Very B",
    price:296.0 ,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
  {
    image_url: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1611937942l/56732449._SX50_.jpg",
    name: "The Love Hypothesis (Paperback)",
    price: 5101.0 ,
    cart_img:"https://www.bing.com/th?id=OIP.ILhpj2TXyR5fR4YO7mMs8QHaH3&w=242&h=257&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
    view: "View Now",
    line_img:"https://th.bing.com/th/id/OIP.6045obu5Er5bZUEjyqvTbAAAAA?pid=ImgDet&rs=1",
    detail:"More details",
  },
]


kartData.forEach(function(ele){
    let div=document.createElement("div");
    let img=document.createElement("img")
    img.src=ele.image_url
    
    let h3=document.createElement("h3")
    h3.innerText=ele.name

    let p=document.createElement("p");
    p.innerText=ele.price
    p.style.color="teal"

    let btn1=document.createElement("button")
    btn1.innerText=ele.view
    btn1.style.color="teal"

    let btn2=document.createElement("button")
    btn2.innerText=ele.detail
    btn2.style.color="teal"

    div.append(img,h3,p,btn1,btn2)
    document.querySelector("#cantainer").append(div)
})